### ISSUE TITLE
New workflows permission for nixpkgs' backport app

### ISSUE THREAD

**Issue by wolfgangwalther** [nix-open-org/org-v2#125]
The GitHub app for nixpkgs' backports needs the `workflows` permission to be able to backport changes to some of the workflow files.

See https://github.com/NixOS/nixpkgs/pull/415680#issuecomment-2961606623.

nixvim had the same issue, solved the same way: https://github.com/nix-community/nixvim/issues/3429

**Comment by zimbatm** [comment]
Done!

**Comment by wolfgangwalther** [comment]
@NixOS/org can you confirm that the `nixpkgs-ci` App has the `workflows` privilege correctly set?

We are seeing the same kind of failures again:

```
! [remote rejected]     backport-432842-to-release-25.05 -> backport-432842-to-release-25.05 (refusing to allow a GitHub App to create or update workflow `.github/workflows/build.yml` without `workflows` permission)
```

**Comment by wolfgangwalther** [comment]
It's the app that is referenced via `NIXPKGS_CI_APP_ID`, if that helps.

**Comment by zimbatm** [comment]
App ID: 1075715

<img width="1263" height="901" alt="Image" src="https://github.com/user-attachments/assets/26a70ed5-d2f6-4ed5-8131-819769b3d082" />

**Comment by wolfgangwalther** [comment]
Hm, yeah, that looks exactly right. No idea why this error persists.

**Comment by wolfgangwalther** [comment]
@MattSturgeon did the workflows permission work for you for nixvim in the end?

**Comment by wolfgangwalther** [comment]
Ah, I think I know why. We have the privilege, but we are not using it, yet:

```
      - uses: actions/create-github-app-token@0f859bf9e69e887678d5bbfbee594437cb440ffe # v2.1.0
        id: app-token
        with:
          app-id: ${{ vars.NIXPKGS_CI_APP_ID }}
          private-key: ${{ secrets.NIXPKGS_CI_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
```

We will need to add the workflow permission here, so that the **token** we receive has it as well.

My bad, sorry for the noise!
